name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest

    steps:
    - uses: actions/checkout@v3
    - name: Frontend
      run: cd src/frontend && cargo test --verbose
    - name: Backend
      run: cd src/src-tauri && cargo test --verbose