name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest

    steps:
    - uses: actions/checkout@v3
    - name : Install basic packages
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - name: Build
      run: cd src/frontend && cargo build --verbose
    - name: Run tests
      run: cd src/src-tauri && cargo test --verbose
