name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : Install basic packages
      run: sudo apt-get update; sudo apt install libgtk-4-dev 
    - name: Build
      run: cd src/frontend && cargo build --verbose
    - name: Run tests
      run: cd src/src-tauri && cargo test --verbose
